main/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from .views import MainView, ProductDetailView, ProductsListView, UserLoginView, UserPageView, AddProductInShoppingCart, \
    DelProductsInShoppingCart, DelProductInShoppingCart, AddOrder, OrderView, UserRegistrationView, AdminPanelPageView, \
    AdminPanelOrdersView, AdminPanelUsersView, AdminPanelUserOrdersView, AdminOrderView, AdminPanelProductsView, \
    AdminPanelAddProductView, AdminPanelProductView, AdminPanelAddImageView, EditQuanProductInShoppingCart, \
    AddAddressOrder, SetStatusOrder, SetTrackNum, DelProduct, AdminPanelEditProductView, AdminPanelEditProductPageView, \
    UserPageInfoView, UserUpdateInfoView, UserChangePasswordView, EditQuanProductInOrder, AdminPanelUpdateImageView, \
    AboutUsView, DeliveryView, DelProductView

urlpatterns = [
    path('', MainView.as_view(), name='main_url'),
    path('about-us', AboutUsView.as_view(), name='about_us_url'),
    path('delivery', DeliveryView.as_view(), name='delivery_url'),
    path('', MainView.as_view(), name='main_url'),
    path('products/<int:pk>', ProductsListView.as_view(), name='product_list_url'),
    path('products/product/<int:pk>', ProductDetailView.as_view(), name='product_detail_url'),
    path('shopping-card/add/<int:pk>', AddProductInShoppingCart.as_view(), name='add_prod_in_sc_url'),
    path('shopping-card/edit/quantity/<int:pk>', EditQuanProductInShoppingCart.as_view(), name='edit_quan_prod_in_sc_url'),
    path('shopping-card/delete/all', DelProductsInShoppingCart.as_view(), name='del_all_prod_in_sc_url'),
    path('shopping-card/delete/<int:pk>', DelProductInShoppingCart.as_view(), name='del_prod_in_sc_url'),
    path('order/create', AddOrder.as_view(), name='create_order_url'),
    path('order/create/address-add/<int:pk>', AddAddressOrder.as_view(), name='create_address_order_url'),
    path('order/<int:pk>', OrderView.as_view(), name='view_order_url'),
    path('user-page', UserPageView.as_view(), name='user_page_url'),
    path('user-page/info', UserPageInfoView.as_view(), name='user_page_info_url'),
    path('user-page/info/update', UserUpdateInfoView.as_view(), name='user_page_update_info_url'),
    path('user-page/password/', UserChangePasswordView.as_view(), name='user_password_change_url'),

    path('login', UserLoginView.as_view(), name='login_url'),
    path('logout', LogoutView.as_view(), name='logout_url'),
    path('registration', UserRegistrationView.as_view(), name='registration_url'),

    path('admin-panel', AdminPanelPageView.as_view(), name='admin_panel_url'),
    path('admin-panel/orders', AdminPanelOrdersView.as_view(), name='admin_panel_orders_url'),
    path('admin-panel/orders/order/<int:pk>', AdminOrderView.as_view(), name='admin_panel_order_url'),
    path('admin-panel/status-order/<int:pk>', SetStatusOrder.as_view(), name='set_status_order_url'),
    path('admin-panel/order/track-num/<int:pk>', SetTrackNum.as_view(), name='set_track_num_order_url'),
    path('admin-panel/order/quantity/o=<int:pk>&p=<int:product>', EditQuanProductInOrder.as_view(), name='edit_quan_order_url'),
    path('admin-panel/users', AdminPanelUsersView.as_view(), name='admin_panel_users_url'),
    path('admin-panel/users/user/<int:pk>', AdminPanelUserOrdersView.as_view(), name='admin_panel_user_orders_url'),
    path('admin-panel/products', AdminPanelProductsView.as_view(), name='admin_panel_products_url'),
    path('admin-panel/products/add', AdminPanelAddProductView.as_view(), name='add_product_admin_url'),
    path('admin-panel/products/edit/<int:pk>', AdminPanelEditProductView.as_view(), name='edit_product_admin_url'),
    path('admin-panel/products/edit/p=<int:pk>', AdminPanelEditProductPageView.as_view(), name='edit_product_p_admin_url'),
    path('admin-panel/products/delete/<int:pk>', DelProduct.as_view(), name='del_product_admin_url'),
    path('admin-panel/products/del/<int:pk>', DelProductView.as_view(), name='del_prod_admin_url'),
    path('admin-panel/products/product/<int:pk>', AdminPanelProductView.as_view(), name='product_admin_url'),
    path('admin-panel/products/product/<int:pk>/add-image', AdminPanelAddImageView.as_view(), name='add_product_image_admin_url'),
    path('admin-panel/products/product/<int:product>/edit-image/<int:pk>', AdminPanelUpdateImageView.as_view(), name='update_product_image_admin_url'),

]

onlinestore/urls.py
from django.contrib import admin
from django.urls import path, include
from .settings import DEBUG, STATIC_URL, MEDIA_URL, STATIC_ROOT, MEDIA_ROOT
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

if DEBUG:
    urlpatterns += static(STATIC_URL, document_root=STATIC_ROOT)
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

main/models.py
import os
from decimal import Decimal

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.dispatch import receiver
from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField

from .managers import CustomUserManager


class CustomUser(AbstractUser):
    """
        Кастомный пользователь
    """

    username = models.CharField(
        max_length=20,
        db_index=True,
        unique=True,
        null=True,
        blank=True,
        verbose_name='Имя пользователя'
    )

    email = models.EmailField(
        unique=True,
        db_index=True,
        verbose_name='E-mail адрес'
    )

    surname = models.CharField(
        blank=True,
        max_length=50,
        verbose_name='Фамилия',
    )

    first_name = models.CharField(
        blank=True,
        max_length=50,
        verbose_name='Имя',
    )

    phone_number = PhoneNumberField(
        null=True,
        blank=True,
        unique=True,
        verbose_name='Номер телефона'
    )

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return f'{self.surname} {self.first_name} {self.email}'

    class Meta:
        ordering = ['-pk']

class Category(models.Model):
    """
        Категории
    """
    category = models.ForeignKey(
        'self',
        on_delete=models.CASCADE,
        verbose_name='Главная категория',
        null=True,
        blank=True,
        related_name='main_category'
    )

    title = models.CharField(
        max_length=50,
        verbose_name='Наименование категории'
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product_list_url', kwargs={'pk': self.pk})

    class Meta:
        verbose_name_plural = 'Категории'


class Product(models.Model):
    """
        Продукт
    """

    title = models.CharField(
        max_length=200,
        verbose_name='Наименование товара'
    )

    description = models.CharField(
        max_length=500,
        verbose_name='Описание товара'
    )

    cost = models.DecimalField(
        verbose_name='Стоимость за ед.',
        decimal_places=2,
        max_digits=6
    )

    vendor_code = models.CharField(
        max_length=10,
        verbose_name='Артикул',
        default=None
    )

    characteristics = models.CharField(
        max_length=256,
        verbose_name='Характеристики',
        null=True,
        blank=True
    )

    category = models.ManyToManyField(
        Category,
        verbose_name='Категории',
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product_detail_url', kwargs={'pk': self.pk})

    class Meta:
        verbose_name_plural = 'Товары'
        ordering = ['-pk']


class ImageProduct(models.Model):
    """
        Изображение продукта
    """

    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE
    )

    title = models.CharField(
        max_length=50,
        verbose_name='Название изображения',
        null=True,
        blank=True
    )

    is_main = models.BooleanField(
        default=False,
        verbose_name='Это главное изображение?'
    )

    image = models.ImageField(
        upload_to='images/',
        verbose_name='Изображение'
    )

    def __str__(self):
        if self.title:
            return self.title
        return f'Изображение {self.pk}'

    def get_product_url(self):
        return reverse('product_detail_url', kwargs={'pk': self.product.pk})

    class Meta:
        verbose_name_plural = 'Изображения товаров'
        ordering = ['-pk']


# These two auto-delete files from filesystem when they are unneeded:
@receiver(models.signals.post_delete, sender=ImageProduct)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    Deletes file from filesystem
    when corresponding `MediaFile` object is deleted.
    """
    if instance.image:
        if os.path.isfile(instance.image.path):
            os.remove(instance.image.path)


@receiver(models.signals.pre_save, sender=ImageProduct)
def auto_delete_file_on_change(sender, instance, **kwargs):
    """
    Deletes old file from filesystem
    when corresponding `MediaFile` object is updated
    with new file.
    """
    if not instance.pk:
        return False
    try:
        old_file = ImageProduct.objects.get(pk=instance.pk).image
    except ImageProduct.DoesNotExist:
        return False
    new_file = instance.image
    if not old_file == new_file:
        if os.path.isfile(old_file.path):
            os.remove(old_file.path)


class ShoppingCart(models.Model):
    """
        Корзина
    """

    user = models.OneToOneField(
        CustomUser,
        on_delete=models.CASCADE,
        verbose_name='Пользователь'
    )

    sum_without_discount = models.DecimalField(
        verbose_name='Сумма корзины без учета скидки',
        decimal_places=2,
        max_digits=6,
        null=True,
        blank=True
    )

    sum_with_discount = models.DecimalField(
        verbose_name='Сумма корзины с учетом скидки',
        null=True,
        decimal_places=2,
        max_digits=6,
        blank=True
    )

    date_created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата создания корзины'
    )

    def __str__(self):
        return f'Корзина пользователя {self.user}'

    class Meta:
        verbose_name_plural = 'Корзины'


class AbstractPlaceProduct(models.Model):
    """
        Абстрактная модель для размещения товаров в корзине и заказе
    """
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        verbose_name='Товар'
    )

    cost_without_discount = models.DecimalField(
        verbose_name='Стоимость без учета скидки',
        decimal_places=2,
        max_digits=6,
        null=True,
        blank=True
    )

    cost_with_discount = models.DecimalField(
        verbose_name='Стоимость с учетом скидки',
        decimal_places=2,
        max_digits=6,
        null=True,
        blank=True
    )

    quantity = models.PositiveIntegerField(
        default=1,
        verbose_name='Количество'
    )

    final_cost = models.DecimalField(
        verbose_name='Общая сумма',
        decimal_places=2,
        max_digits=6,
        null=True,
        blank=True
    )

    class Meta:
        abstract = True


class ProductInShoppingCart(AbstractPlaceProduct):
    """
        Товары в корзине
    """

    shopping_cart = models.ForeignKey(
        ShoppingCart,
        on_delete=models.CASCADE,
        verbose_name='Корзина'
    )

    def __str__(self):
        return f'{self.product} в {self.shopping_cart}'

    def save(self, *args, **kwargs):
        if self.cost_with_discount:
            self.final_cost = self.cost_with_discount * Decimal(self.quantity)
        elif self.cost_without_discount:
            self.final_cost = self.cost_without_discount * Decimal(self.quantity)
        return super().save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Товары в корзине'


class Order(models.Model):
    """
        Заказ
    """

    user = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        verbose_name='Пользователь'
    )

    address = models.CharField(
        max_length=350,
        verbose_name='Адрес',
        null=True,
    )

    date_created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата создания заказа'
    )

    track_num = models.CharField(
        max_length=30,
        verbose_name='Трек номер',
        null=True,
        blank=True,
        default=''
    )

    shopping_cart = models.ForeignKey(
        ShoppingCart,
        on_delete=models.CASCADE,
        verbose_name='Корзина'
    )

    amount = models.DecimalField(
        verbose_name='Сумма заказа',
        decimal_places=2,
        max_digits=6,
        null=True,
        blank=True
    )

    def __str__(self):
        return f'{self.user} от {self.date_created}'

    def get_success_url(self):
        return reverse('view_order_url', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-pk']
        verbose_name_plural = 'Заказы'


class ProductInOrder(AbstractPlaceProduct):
    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE,
        verbose_name='Заказ'
    )

    def __str__(self):
        return f'{self.product} в {self.order}'

    class Meta:
        verbose_name_plural = 'Товары в заказе'


STATUS_CHOICES = [
    ('НП', 'Не подтвержден'),
    ('П', 'Принят'),
    ('О', 'Отправлен'),
    ('ПК', 'Принят клиентом'),
]


class StatusOrder(models.Model):
    status = models.CharField(
        choices=STATUS_CHOICES,
        verbose_name='Статус заказа',
        max_length=10
    )

    order = models.ForeignKey(
        Order,
        verbose_name='Заказ',
        on_delete=models.CASCADE
    )

    datetime_add = models.DateTimeField(
        auto_now_add=True
    )

    def __str__(self):
        return f'{self.order}: {self.status}'

    class Meta:
        verbose_name = 'Статус заказа'
        verbose_name_plural = 'Статусы заказов'

main/templates/main/adminpanel/orders/change_quan.html
{% extends 'main/base_admin.html' %}
{% load static %}

{% block title %}
   Админ-панель | Изменить количество товара
{% endblock %}

{% block add_nav_link %}
{% endblock %}

{% block content %}
<section class="mt-5 mb-5">
    <div class="container">
      <div class="row justify-content-center">
            <div class="col-4 mb-1">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-my w-100 mt-2">Сохранить</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

main/templates/main/adminpanel/orders/order.html
{% extends 'main/base_admin.html' %}
{% load static %}

{% block title %}
   Админ-панель | Заказ {{ order.pk }}
{% endblock %}

{% block add_nav_link %}
{% endblock %}

{% block content %}
<section class="mt-5 mb-5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class=" card order-card">
                  <div class="card-body">
                    <h1 class="card-title text-center title-order"><strong>Заказ №{{ order.pk }}</strong></h1>
                    <h5 class="card-text">Дата заказа: <strong>{{ order.date_created }}</strong></h5>
                    {% if order.address %}
                    <h5 class="card-text">Адрес доставки: <strong>{{ order.address }}</strong></h5>
                      {% else %}
                    <h5 class="card-text">Адрес доставки: <strong>не указан</strong></h5>
                      {% endif %}
                      {% if status.get_status_display %}
                    <h5 class="card-text">Статус заказа: <strong>{{ status.get_status_display }}</strong><a class="btn btn-my btn-sm" data-bs-target="#change_status" data-bs-toggle="modal" type="button" href="#">Изменить статус</a></h5>
                      {% else %}
                    <h5 class="card-text">Статус заказа: <strong>не указан</strong></h5>
                      {% endif %}
                      <h5 class="card-text">
                        Трек-номер отслеживания (СДЕК/Почта России):
                        {% if not order.track_num %}
                            <small>информация появится позже</small>
                        {% else %}
                            <strong>{{ order.track_num }}</strong>
                        {% endif %}
                        <a class="btn btn-my btn-sm" data-bs-target="#change_track_num" data-bs-toggle="modal" type="button" href="#">Изменить трек-номер</a>
                    </h5>
                      <div class="col">
                          <hr>
                          <h4 class="mt-2">Состав заказа: </h4>
                          <table class="table">
                              <thead>
                                <tr>
                                  <th scope="col">{{ forloop.counter}}</th>
                                  <th scope="col">Наименование</th>
                                  <th scope="col">Стоимость ₽</th>
                                  <th scope="col">Количество</th>
                                  <th scope="col">Сумма ₽</th>
                                </tr>
                              </thead>
                              <tbody>
                              {% for product in products %}
                                <tr>
                                  <th scope="row">{{ forloop.counter }}</th>
                                  <td>{{ product.product.title }}</td>
                                  <td>
                                      {% if product.cost_with_discount %}
                                        {{ product.cost_with_discount }}
                                      {% else %}
                                        {{ product.cost_without_discount }}
                                      {% endif %}
                                  </td>
                                  <td>
                                      {{ product.quantity }}
                                      <a class="btn btn-my btn-sm usr" href="{% url 'edit_quan_order_url' pk=order.pk product=product.product.pk %}" role="button">Редактировать</a>
                                  </td>
                                  <td>{{ product.final_cost }}</td>
                                </tr>
                              {% endfor %}
                              </tbody>
                            </table>
                        <div class="col mt-5">
                            <h3>Сумма заказа: {{ order.amount }} ₽</h3>
                        </div>
                      </div>
                      <div class="col"><a href="{% url 'admin_panel_orders_url' %}" class="btn btn-my btn-sm float-end mb-2">Назад</a></div>
                  </div>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="modal fade" id="change_status" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Изменить статус</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          <div class="row justify-content-center">
              <div class="col-5">
                 <form action="{% url 'set_status_order_url' pk=order.pk %}" method="post">
                    {% csrf_token %}
                    {{ form_status.as_p }}
                    <button type="submit" class="btn btn-my w-100 mb-2">Сохранить</button>
                 </form>
              </div>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="change_track_num" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="track_num_title">Изменить трек-номер</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          <div class="row justify-content-center">
              <div class="col-5">
                 <form action="{% url 'set_track_num_order_url' pk=order.pk %}" method="post">
                    {% csrf_token %}
                    {{ form_track_num.as_p }}
                    <button type="submit" class="btn btn-my w-100 mb-2">Сохранить</button>
                 </form>
              </div>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main/templates/main/adminpanel/orders/orders.html
{% extends 'main/base_admin.html' %}
{% load static %}

{% block title %}
   Админ-панель | Заказы
{% endblock %}


{% block search %}
<form class="d-flex mx-3">
    <input class="search-input form-control me-2" type="search"
         {% if search_query %}
           value="{{ search_query }}"
         {% else %}
           value=""
         {% endif %}
         placeholder="№/Email/дата создания (ГГГГ-ММ-ДД)/адрес/трек"
         name="search" aria-label="Search"
  >
  <button class="btn search-btn" type="submit">Поиск</button>
</form>
{% endblock %}

{% block content %}
<section class="mt-5">

    <div class="container">
      <h1 class="mb-4">Заказы:</h1>
          <table class="table table-hover">
  <thead class="thead-dark">
    <tr class="text-center">
      <th scope="col">#</th>
      <th scope="col">Email пользователя</th>
      <th scope="col">Дата создания</th>
      <th scope="col">Адрес</th>
      <th scope="col">Трек номер</th>
      <th scope="col">Сумма заказа</th>
      <th scope="col">Просмотреть</th>
    </tr>
  </thead>
      {% for order in orders_p.object_list %}
  <tbody>
    <tr class="text-center">
      <th scope="row" class="align-middle">{{ order.pk }}</th>
      <td class="align-middle">{{ order.user.email }}</td>
      <td class="align-middle">{{ order.date_created }}</td>
      <td class="align-middle">{{ order.address }}</td>
      <td class="align-middle">{{ order.track_num }}</td>
      <td class="align-middle">{{ order.amount }}</td>
      <td class="align-middle"><a class="btn btn-my usr" href="{% url 'admin_panel_order_url' pk=order.pk %}" role="button">Посмотреть</a></td>
    </tr>
  </tbody>
    {% endfor %}
</table>
  <nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {% for n in orders_p.paginator.page_range %}
    {% if orders_p.number == n%}
      <li class="page-item active"><a class="page-link" href="?page={{ n }}">{{ n }}</a></li>
    {% else %}
      <li class="page-item"><a class="page-link" href="?page={{ n }}">{{ n }}</a></li>
    {% endif %}
    {% endfor %}
  </ul>
</nav>
    </div>
</section>
{% endblock %}